### ISSUE TITLE
-bash: countdown: command not found

### ISSUE THREAD

**Issue by bofeiw** [antonmedv/countdown#10]
After installing go and do the install command, I still could not run countdown in Mac terminal, what's happening?

<img width="682" alt="Screen Shot 2019-05-07 at 4 52 34 pm" src="https://user-images.githubusercontent.com/34177142/57277991-b1d8a680-70e8-11e9-8fe5-200a665ffe76.png">

**Comment by antonmedv** [comment]
Make sure bin in $PATH.

**Comment by bofeiw** [comment]
Sorry about late reply.
It works for me now. I manually cd into `~/go/bin` and then typed `countdown`.
Im new to go, and struggled a while before get it works. If the install script automatically add bin into PATH, it will save new goers a lot of time. Would you consider this feature? @antonmedv ?

**Comment by antonmedv** [comment]
This is go feature. Make sure you properly installed go, ie added bin to path.

**Comment by bofeiw** [comment]
Thanks.

**Comment by jakob1379** [comment]
for other people who end up here:

If go/bin is not in your path, you can add it by ````/bin` 

``export PATH=${PATH}:`go env GOPATH`/bin``
