### ISSUE TITLE
Cannot pause

### ISSUE THREAD

**Issue by jakob1379** [antonmedv/countdown#15]
I downloaded the latest version and when trying to pause the timer I can't. The keypresses are elsewhere. I'd gladly help debug if I get told how to.

**Comment by falsified** [comment]
Same issue here

**Comment by antonmedv** [comment]
Use debugger! ;)

**Comment by pipecleaner** [comment]
It is correct - neither "p" nor "P" will pause (linux 32 bit)

**Comment by antonmedv** [comment]
¯\_(ツ)_/¯

**Comment by sneak** [comment]
Suggestion: add spacebar as a method of pause/unpause toggle (the default in most apps that have pause).  Also, suggest adding some sort of onscreen indication of pause (such  `(paused)` in normal text below the numbers).

**Comment by antonmedv** [comment]
Awesome idea. Anyone willing to contribute?

**Comment by tlboright** [comment]
> Awesome idea. Anyone willing to contribute?

I'd love to.  Do you mind assigning to me @antonmedv?

**Comment by antonmedv** [comment]
Sure

**Comment by tlboright** [comment]
This issue should be resolved by the following PR:
https://github.com/antonmedv/countdown/pull/32

I think we can close this issue.
