### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by abedjaber** [antonmedv/countdown#16]
Hello,
I cloned the repo, but How can I install it, or run it?
Im new at Linux, I have Kali linux installed.
Many thanks

**Comment by lakuapik** [comment]
i just installed on my gnu/linux debian machine. here is what i do:

1. go to release page, here https://github.com/antonmedv/countdown/releases
2. find your machine architecture, mine 64-bit so i choose `linux_amd64`
3. download the file and put in `/usr/local/bin` folder:
    ``` sh
    sudo wget -c https://github.com/antonmedv/countdown/releases/download/v1.0.0/countdown_linux_amd64 -O /usr/local/bin/countdown
    ```
4. make the file executable ```sudo chmod +x /usr/local/bin/countdown```
5. run it `countdown 5s`

#cmiiw

**Comment by ThomasSeeker** [comment]
Hey, 

the method of lakuapik above seems outdated.

How can I install now, after I downloaded and extracted the zip-file?
