### ISSUE TITLE
feature request: please beep on completion

### ISSUE THREAD

**Issue by sneak** [antonmedv/countdown#24]
alternately, if you don't want to make it annoying by default, have it look at `COUNTDOWN_ON_ZERO_COMMAND` in the environment, so I can do:

```
export COUNTDOWN_ON_ZERO_COMMAND='echo -e "\a"'
```

in my `.profile`.

**Comment by antonmedv** [comment]
Try function () countdown $@ | beep

**Comment by tlboright** [comment]
I do something similar to this.

I wrote a custom bash function that takes the input of the kitchen time and plays an OS-specific audio file when finished.

```bash
alias endSound="cmd_to_play_sound sound_file_to_play"

function cod () {
    countdown "$1" && endSound
}
```

I add this to .profile and use the function as follows:

```
  $ cod $@
```

Playing audio in the different OSs is possible, but often requires you to install dependency libraries anyway.

It's probably better (and more customizable!) for you to create your own function and call that from your shell.

**Comment by antonmedv** [comment]
Solution for macOS

    countdown 1s && say beep
