### ISSUE TITLE
invalid duration or kitchentime - with a valid input

### ISSUE THREAD

**Issue by jakob1379** [antonmedv/countdown#31]
To replicate:
```sh
❯ date
2023-02-08T08:24:24 CET
❯ countdown 14:15
error: invalid duration or kitchentime: 14:15
```
Expected behaviour:
should be the same as the command
```sh
❯ countdown 02:15PM
```

**Comment by tlboright** [comment]
@jakob1379 I'm not able to reproduce this.

Please see the attached video.  
Note: I also tested with combinations of hours and minutes and didn't see any issues.


[Screencast from 03-04-2023 04:55:18 PM.webm](https://user-images.githubusercontent.com/6128522/222935852-51f8d659-c056-410b-ac8a-528950096b06.webm)

**Comment by antonmedv** [comment]
@tlboright thanks for debugging !

**Comment by jakob1379** [comment]
> @tlboright thanks for debugging !

So the problem is still in my end, tried with different terminals, disabling my bashrc, running in zsh

**Comment by jakob1379** [comment]
Updated to the latest version which solved the issue
