### ISSUE TITLE
1h2m3s will be format to 2m3s

### ISSUE THREAD

**Issue by shaohui10086** [antonmedv/countdown#7]
https://github.com/antonmedv/countdown/blob/f9011555776dc89f944de398334b555c82b52f25/main.go#L56

d.Hours() will always return 0, because it is not the origin input

**Comment by antonmedv** [comment]
Can you send PR to fix it?

**Comment by mingrammer** [comment]
Sorry, it was caused by my mistake.

**Comment by mingrammer** [comment]
I fixed it with #8

**Comment by antonmedv** [comment]
Thanks!
