### ISSUE TITLE
I dont know what to "say"...

### ISSUE THREAD

**Issue by StingyJack** [antonmedv/countdown#9]
``` dos
c:\users\stingyjack\go\bin\countdown 10s && say "final"
```
does the countdown, then...
``` dos
'say' is not recognized as an internal or external command,
operable program or batch file.
```

I'm guessing I need another tool installed for that. What am I missing?

**Comment by ShawnMilo** [comment]
`say` is a Mac command. It won't work on Windows. Replace with whatever text-to-speech software you like.

**Comment by Ruben35** [comment]
You could use `echo`

**Comment by StingyJack** [comment]
my google-fu skills were failing me that day

**Comment by RealYukiSan** [comment]
```
$ countdown

 countdown [-up] [-say] <duration>

 Usage
  countdown 25s
  countdown 14:15
  countdown 02:15PM

 Flags
  -say
        announce the time left
  -up
        count up from zero
```

any info what is the function of `-say` flag? I tried it and see no effect
